#
# Module manifest for module 'Write-Module'
#
# Generated by: theosomos@gmail.com
#
# Generated on: 02/04/14
# Modified on:  09/20/17
#
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '2016.9.20.1'

# ID used to uniquely identify this module
GUID = '156c9774-13a3-4995-beb0-d9ed790b20fb'

# Author of this module
Author = 'theosomos@gmail.com'

# Company or vendor of this module
CompanyName = 'ToddleSoft'

# Copyright statement for this module
Copyright = '(c) 2016 ToddleSoft. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A module demonstrating proxy classes and callstack traversal for logging/debugging purposes by ToddleSoft'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = '5.0'

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('Write-Module.psm1')

# Functions to export from this module
FunctionsToExport = 'Write-Debug','Set-DebugPreference','Set-InformationPreference'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @('Write-Module.psm1')

# List of all files packaged with this module
FileList = 'Write-Module.psm1', 'Write-Module.psd1'

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

